---
repos:
    # Python: CodeFormatter
    - repo: https://github.com/psf/black
      rev: 23.1.0
      hooks:
          - id: black

    # Python: removes unused import
    - repo: https://github.com/hadialqattan/pycln
      rev: v2.1.3
      hooks:
          - id: pycln
            args: [--config=pyproject.toml]

    # Python: sorts imports
    - repo: https://github.com/pycqa/isort
      rev: 5.12.0
      hooks:
          - id: isort
            args: [--profile, black, --filter-files]

    # Python: checks Pydoc comments
    - repo: https://github.com/pycqa/pydocstyle
      rev: 6.3.0
      hooks:
          - id: pydocstyle
            additional_dependencies: ['pydocstyle[toml]']
            entry: pydocstyle
            language: python
            types: [python]

    # Python: static code analyzer
    # pylint needs to import modules and dependencies to work correctly,
    # the hook only works with a local installation of pylint (in your environment).
    - repo: local
      hooks:
          - id: pylint
            name: pylint
            entry: pylint
            language: system
            types: [python]
            args: [-rn, -sn, --rcfile=pyproject.toml]

    # Python: checks for known vulnerabilities and CVEs
    - repo: https://github.com/PyCQA/bandit
      rev: 1.7.5
      hooks:
          - id: bandit
            args: [-c, pyproject.toml, -r]
            additional_dependencies: ['bandit[toml]']

    # General: formatting of yaml files
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.2
      hooks:
          - id: yamlfmt

    # General: linting of Yaml files
    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.29.0
      hooks:
          - id: yamllint
            args: [-c, .yamllint-config.yml]
